### ISSUE TITLE
cant find how to determin temperature

### ISSUE THREAD

**Issue by brigita1234** [gtatters/ThermImageJ#12]
Hello, 

I hope its ok to ask here. I have been trying to find a way how to use it for my data analysis but I can't  seem to understand how to find a temperature values of specific places in the image?
What I ideally would like is to select multiple ROI in the thermal image and receive the values as temperature values. Is it possible to do with this plug in please?
I have followed your instructions on the website and everything seems to work, I do get the FLIR calibration values out of my images. But what would be the steps to get the temperature values on the specific parts of the image please?
I would really appreciate if you could please advise me on how to do it please.

Thank you so much !!

**Comment by gtatters** [comment]
Hi Brigita1234

Thanks for the note.  Assuming you have used the FLIR Calibrations Value macro at least once on one of your radiometric jpgs, the calibration values will be saved in memory (Possibly only for the working session, reseting to defaults I have provided for my own camera).  Of course, you could edit the Thermimage.ijm file and change the parameters at the top of the file to your own if you like.

After you have loaded the image using the Import FLIR JPG function, the image will likely be a 16 bit greyscale image.  There is another function called Raw2Temp (this means "convert the raw data to temperature).  When you click on this, it will prompt you for all the image parameters and the calibration values, but it will autofill these values based on what was extracted from your file.  At this stage, it is up to the user to set the image parameters correctly.  It also helps if you have used any of the FLIR softwares since the parameters are explained in their user manuals.  Once you select OK, it will convert the file.  I have two modes to convert.  One mode (Slow) converts the pixels to 32 bit numeric values in degrees celsius.  The Fast mode technically fits a polynomial curve that approximates the raw 2 temp conversion process and allows you to change parameters if you get them wrong the first time.

Hopefully that helps?  If you have a more technical issue, please attach a sample image you are using, since that usually helps me troubleshoot.

**Comment by brigita1234** [comment]
I think I got it now. Thank you so much was very useful. Just a small question - if I get all the calibration values from my image correctly, but I am unable to add the calibration bar, when I click on it it comes up as an error '---RGB and composite images are not supported in line 3979 run ...(''Calibration Bar'' , calibrations<)>;---. Does it affect the accuracy of my results?

Thanks 
Brigita

**Comment by gtatters** [comment]
Hard to say without a better description of work flow or a sample image.  That slightly alarms me that you aren't really working with a radiometric image or you have implemented other changes to the image before applying the calibration bar.  The cal bar is part of imagej, so my macros are pretty simple and won't respond well if you have already changed the image to an RGB.  I would apply the calibration bar to a 32 bit image first, then duplicate and then flatten the overlay and then save/export as an RGB tiff.  But all of these steps are not part of ThermimageJ since they are part of basic imageJ processing.  Hopefully that helps?

**Comment by gtatters** [comment]
> I think I got it now. Thank you so much was very useful. Just a small question - if I get all the calibration values from my image correctly, but I am unable to add the calibration bar, when I click on it it comes up as an error '---RGB and composite images are not supported in line 3979 run ...(''Calibration Bar'' , calibrations<)>;---. Does it affect the accuracy of my results?
> 
> Thanks Brigita

I have finally replicated this error, and found that it happens with FLIR images that are composite Digital/Thermal images. I have no code fix for this, but the simple solution would be to Duplicate the image (from the menu "Image-->Duplicate") from within ImageJ before applying the Calibration bar.  This copy of your image will be the correct image type to allow the inclusion of a calibration bar.
