### ISSUE TITLE
import Flir mp4

### ISSUE THREAD

**Issue by oseynnes** [gtatters/ThermImageJ#2]
**Describe the bug**
When trying to import a Flir mp4 file using "import Flir sequence" I get an error message:
Error:		
Index (-1) is outside of the 0-655 range in line 1830:
PR1 = parseFloat ( substring ( flirvals , indexOf ( flirvals , ":" , indexOf ( flirvals , "Planck R1" ) <)> + 1 , index...

It is perhaps not the right way to open the file?

**To Reproduce**
1. Go to 'File'
2. Click on 'import FLIR SEQ'
3. Select mp4 file

**Expected behavior**
Opening the mp4 file containing a video acquired with a Flir T840

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15.3

**Additional context**

**Comment by gtatters** [comment]
A FLIR mp4 file is not a radiometric file and thus import flir SEQ simply will not work.  Double check your settings on the camera to make sure you are capturing radiometric video files.

**Comment by oseynnes** [comment]
Ok. Sorry for the confusion and thank you for the fast reply!

Le 10 mars 2020 à 11:43, Glenn Tattersall <notifications@github.com> a écrit :

﻿

A FLIR mp4 file is not a radiometric file and thus import flir SEQ simply will not work. Double check your settings on the camera to make sure you are capturing radiometric video files.

**Comment by gtatters** [comment]
sorry about that.  anyhow, I couldn't add functionality for mp4 files since they are compressed, colourised videos and lack the calibration constant information to do any of the calculations in my functions.  You might be able to import the mp4 using the ffpmeg plugin included with FIJI, but that will still be a colour video and you'd need to translate that to temperature using customised solutions.
