### ISSUE TITLE
Issues with raw file import

### ISSUE THREAD

**Issue by LindsayErndwein** [gtatters/ThermImageJ#7]
Hello and thank you for creating this useful package. 

I am attempting to use Thermimage and ThermimageJ in Windows to analyze the internal temperature of cranberries. The Thermimage package worked great in R and I was able to export a CSVs of the image temperature values and accompanying jpegs. 

I would like to measure an average temperature read for each berry and planned to use ThermimageJ for this. I successfully installed ThermimageJ, and all accompanying software and converted my files to raw format using your code provided. However, I am having trouble importing the raw files using the File>Import>Raw path. Below are examples of my original FLIR jpeg and the raw file I imported into ImageJ:

Original:
![20](https://user-images.githubusercontent.com/99741254/154082650-dddd3fcb-f639-4937-818e-9ddbaddfac5f.jpg)
Raw file imported into ImageJ:
![rawIssues](https://user-images.githubusercontent.com/99741254/154082052-c4619a8e-4f50-48f4-bdb3-1cfc5f7be012.PNG)

To investigate further, I tried importing one of your sample raw images and the same thing happened:

![Tattersrawimage](https://user-images.githubusercontent.com/99741254/154083428-89bf1bcc-2fa1-410e-9b87-17761c099b7c.PNG)

I have not changed anything in the ThermimageJ macro code yet. Any idea what the issue might be? 

Thanks,

-Lindsay

**Comment by gtatters** [comment]
I'm not sure why you would import - raw a FLIR formatted jpg. Well, actually there could be raw pixel data in the jpg, but it's not clear where to start the reading of pixel data would be.  Thus the function you want to apply is in the ThermimageJ macros (see screenshot).  Just use my macro to import--FLIR JPG and the file imported properly for me.  I can even see temperature displayed as the pixel intensity since it gets converted to a 32-bit image during the macro import.

<img width="645" alt="Screen Shot 2022-02-15 at 12 14 00 PM" src="https://user-images.githubusercontent.com/11757426/154113748-5f4860e8-5462-4aee-b820-2dab26996590.png">

**Comment by LindsayErndwein** [comment]
Thanks for the quick response. 

So I don't need to convert my FLIR jpegs to raw in R in order to analyze them in ThermimageJ. That makes life easier. 

Tried the macro Import FLIR JPG but got this message. 

![ThermimageJ_Macroerror](https://user-images.githubusercontent.com/99741254/154119960-bea94b65-10d8-4a14-bba7-c76dacb9436f.PNG)

This makes me think the issue might be in the macro installation process, since it worked for you.

**Comment by gtatters** [comment]
That error means that ThermimageJ is failing to extract information from the FLIR JPG.  The macros extract the calibration constants from your JPG using Exiftool, thus the problem might be with your Exiftool install.

Go through the installation checks to make sure you have Exiftool installed as well as the other packages.  

https://github.com/gtatters/ThermImageJ#installation-checks

I wrote this for Mac, and have tried to make compatible with Windows OS, but users should follow up on the peripheral installations on the respective websites for assistance.

**Comment by gtatters** [comment]
You might have seen an older example where I painstakingly converted a single jpg in Thermimage (the R package) and then exported as raw and then imported that into ImageJ.  

But ThermimageJ is my ImageJ macro solution to eliminate the need for the R package step.  But a lot of the heavy lifting is being done by Exiftool which needs to be installed for ImageJ to "call" it

**Comment by LindsayErndwein** [comment]
Thanks for clarifying. 

I typed in ver -exiftool  and the console outputted "12.40", which is a good sign according to your website, but I still get the same error when importing the FLIR JPEG. 

Exiftool doesn't need to be in a certain folder within ImageJ does it?

**Comment by gtatters** [comment]
4 thoughts before going into a 3 hour meeting.  Do you know how to run command line code?  You could try:

```
exiftool.exe Filename.jpg
```
just to verify that exiftool is running properly with your file.  Share the output?

Second thought.  You are trying to import a jpg that hasn't been altered?  FLIR annoyingly call their files .jpg, but they aren't only a jpg, they do contain other info, so it needs to be an original FLIR file.

Could you share the output from the log window that ThermimageJ generates?  Might give me some hints.  I doubt it's my code, as your file worked for me.  It likely is something about your system.

Can you verify if you have any whitespace in character names or folder names?  Difficult for me to write code across 3 OS in ImageJ that doesn't snarl up when it encounters a space.  See some of the other issues people have had.

**Comment by LindsayErndwein** [comment]
1. Okay, I ran the line of code you sent me on the JPEG (changed to the correct directory). 
Output looks good: 

![output1](https://user-images.githubusercontent.com/99741254/154136515-f7d3f47c-2c20-46f0-89a3-88b608e1cd51.PNG)
![output2](https://user-images.githubusercontent.com/99741254/154136520-745bdc79-3c8b-4285-a8a2-caff39aa16e1.PNG)

2. I downloaded these FLIR jpegs directly from the web-based FLIR CamWeb interface (FLIR A70 model). These were captured directly from the camera and are unaltered:
![FLIRCAMWEB](https://user-images.githubusercontent.com/99741254/154136610-1bd52c14-b9fe-438f-8805-cbb05c7fc12e.PNG)

3. Here is the full debug window after Import FLIR JPG:
![Debug1](https://user-images.githubusercontent.com/99741254/154137654-e6620334-bb34-492f-a287-4c8b7e209ebf.PNG)
![Debug2](https://user-images.githubusercontent.com/99741254/154137706-e1eae960-a638-4cc6-b1f4-30cc072dbbe8.PNG)

And the accompanying log window:
![Logwindow](https://user-images.githubusercontent.com/99741254/154138510-64876bf7-a17c-4eb4-a45d-e10cefeccc70.PNG)

4. Do not see any whitespace in the image folder or image filenames.

**Comment by gtatters** [comment]
Hmm...I've never encountered or thought of a . inside a folder name before, and perhaps my code assumes that would not be a normal folder/filename, since . usually is used immediately before the file type designator.  Any chance you can put the jpg in the root c:\ and try loading it from there?   It's possible I have code that strips out . and spaces.

But my version on mac can seemingly handle the . in the file name, so I might be on the wrong track here.  I'm trying to eliminate all other possible potential issues.  the error message isn't that helpful for me...but I'll look at the code to see.

**Comment by gtatters** [comment]
And what happens if you try to run this code in the command line yourself?  See how i've output "copy / paste this into command window to test".

![image](https://user-images.githubusercontent.com/11757426/154148835-7bd7664e-681a-429f-9f0c-952221163363.png)

**Comment by gtatters** [comment]
did you change the default working directories in the Thermimage.ijm file to the appropriate folders on your system?  Maybe that is why it's having trouble?  Although, I trust that exiftool is formally installed in the c:\windows folder.

https://github.com/gtatters/ThermImageJ#setting-and-verifying-paths-to-command-line-tools

**Comment by LindsayErndwein** [comment]
If I run in command window I get this:
![commandwindow](https://user-images.githubusercontent.com/99741254/154151293-0a26df6d-acb5-4d9b-9b3f-729220a4bf21.PNG)

I did not change working directories in the Thermimage.ijm file. Maybe that is the issue. Where in the macro code would that be?

**Comment by gtatters** [comment]
close to the top with lines on the right asking user to "verify this". 

Approximately line 113

Might have been cleaner way to ensure the path was there by default, but exiftool can be run however user wishes to install it.

**Comment by gtatters** [comment]
it's possible you need to change
var exiftoolpathWindows="c:/windows/"; 
to
var exiftoolpathWindows="c:/windows/system32";

But it depends on where you installed exiftool.exe

**Comment by LindsayErndwein** [comment]
I see it now, thank you. (Apologies for my amateur coding ability) Will let you know if this works.

**Comment by gtatters** [comment]
no problem. 

maybe
```dir exiftool.exe```

will tell you what the path is in windows.  I forget. on mac/linux it's:

```where exiftool```

**Comment by gtatters** [comment]
if that solves the issue, you won't know unless you restart fiji or relaunch the toolset.  Restart is easier to explain than relaunch.

**Comment by LindsayErndwein** [comment]
Well this is weird, file not found? Both perl and exiftool are on my desktop.  

![output](https://user-images.githubusercontent.com/99741254/154152868-41f21306-3599-4c7a-8b39-a5914abffb82.PNG)

(I'm going home for the day but will check this tomorrow)

**Comment by gtatters** [comment]
at least for exiftool, I would follow Phil Harvey's explanation for how to install it in the c:\windows folder.  

Perl is less important for you if you're only doing images.  I wrote some perl script to split up thermal video files (Perl was the only language I could figure out).  

from Exiftool website:

Stand-Alone Executable
Download the Windows Executable from the [ExifTool home page](https://exiftool.org/index.html).
(The file you download should be named "exiftool-12.40.zip".)
Extract "exiftool(-k).exe" from the ".zip" file, and place it on your Desktop.
(Double-click on "exiftool-12.40.zip" to open the archive, then drag "exiftool(-k).exe" to your Desktop.)
You can now double-click on "exiftool(-k).exe" to read the application documentation, or drag-and-drop files and folders to run exiftool on selected files. To install exiftool for use from the command line, continue with the following steps:

Rename "exiftool(-k).exe" to "exiftool.exe".
(or "exiftool(-k)" to "exiftool" if file name extensions are hidden on your system)
Move "exiftool.exe" to the "C:\WINDOWS" directory (or any other directory in your PATH).
You can now run exiftool by typing "exiftool" at the command prompt. (To get to the command prompt, select "Run..." from the Windows "Start" menu, then type "cmd" and press Return.)

Notes:

In Windows 7, running exiftool may require administrator privileges. If necessary, this may be enabled by right clicking on exiftool, then selecting "Run this program as administrator" from the Compatibility settings.
Windows 10 users have sometimes reported that exiftool hangs when run. This may be due to Windows Defender blocking or slowing down exiftool. To solve this, either disable Windows Defender or add an exclusion for exiftool (but note that exiftool may still run more slowly if you just add an exclusion).
Occasionally users have reported that exiftool gives errors when running this version for this first time. It is possible this may happen if the installation process gets interrupted. In this case, follow the Uninstalling instructions below then re-install exiftool. Be sure that you have sufficient disk space in your TEMP directory for exiftool to unpack about 12 MB of temporary files -- these are the Perl libraries used by the exiftool application which are unpacked the first time exiftool is run.

**Comment by LindsayErndwein** [comment]
It worked! The path was the issue. I reinstalled exiftool.exe, put it in my user folder, and changed the ThermimageJ macro code to be consistent with the exiftool path. The image loaded perfectly. 

Thank you so much for your help and patience.

**Comment by LindsayErndwein** [comment]
One last question, If I use Analyze > measure after selecting the area of each berry, will the mean in the output window reflect the mean temperature of the region?

**Comment by gtatters** [comment]
excellent!  I probably should have shared my youtube video showing how to install it all in the beginning!

As for the Analyse--> Measure question, yep, that's how ImageJ measures things.  You might need to set up your measurements first (Analyse-->Set Measurements) and select what outputs you want (Mean, Median, SD etc).

I wrote some macros that do this measuring for you, but my macros were written for measuring thermal images of bird bills, so if you draw a circle around your object and hit the number 1,2,3,4,5, or 6, you'll get an automatically populated table.  You could even edit the Thermimage.ijm file and rename those shortcuts to a custom object name if you wish.

I still haven't put a tutorial together for this.  Many of the features in it are ImageJ features that other imageJ users are well familiar with, which is why I haven't yet done that.

**Comment by gtatters** [comment]
also those short cut measuring macros automatically save your output to a .csv file on your desktop so you don't lose your progress!  User beware mind you if it over-writes.

**Comment by LindsayErndwein** [comment]
Awesome. I will definitely keep an eye out for any tutorials that you share. This program is really useful and accessible to scientists on a budget. 

Again, I am super grateful for all your help. Will definitely cite your work in our upcoming paper in cranberry research. :)

**Comment by gtatters** [comment]
i'll close the issue for now.  feel free to comment further if you wish.  glad you find it useful!  that means a lot.
