### ISSUE TITLE
No byte swap for FLIR png with new "Import with defaults"

### ISSUE THREAD

**Issue by KlMichel** [gtatters/ThermImageJ#8]
**Hello Glenn,**
thanks a lot that you took the time to add the "Import FLIR JPG with defaults" with ThermimageJ-2.6. Being a bit lazy, I realized this not before yesterday.
However, I found that it works nicely with FLIR tiff files but it fails to perform the "byte swap" for png files. As a workaround I added the following lines in your code (after line 1191):

	if(RawThermalType == "PNG" && ConvertWithDefault == "yes"){
	run("Byte Swapper");
	}

I tested it with the sample files that are included in "ThermImageJ-2.6" and my image files. Both the normal import (with parameter dialog) and the new import with defaults seem to work but probably it can be done more elegant.

Best, Klaus

**Comment by gtatters** [comment]
Hi Klaus
Sorry I'm in the field and travelling away from computer a lot so will see about adding this in a future update.  I'm glad you figured out a work-around - it suggests my code is somewhat decipherable.  

Reasons why I have been hesitant to do this particular decision when importing is because I am not convinced that FLIR is ever consistent in the byte ordering between cameras or software.  Thus, if I assume the PNG style data need to have the byte order swapped, I suspect we'll find a different image from a different flir camera that doesn't need it!  So I might add your suggestion but need to keep an eye out in case it breaks import for some other files.  

Best
Glenn

**Comment by gtatters** [comment]
ok, I've added your code to v2.7.

Tested with a number of images I have and it seems to work.  

Thanks for the suggestion!

**Comment by KlMichel** [comment]
Hi Glenn,
I am glad it works! We take our images with one camera in a controlled environment and the parameters will not change between sessions but I will keep an eye on it (especially if there are any firmware updates).

All the best,
Klaus

Von: Glenn Tattersall ***@***.***>
Gesendet: Freitag, 15. Juli 2022 03:40
An: gtatters/ThermImageJ ***@***.***>
Cc: Klaus Michel ***@***.***>; Author ***@***.***>
Betreff: Re: [gtatters/ThermImageJ] No byte swap for FLIR png with new "Import with defaults" (Issue #8)


ok, I've added your code to v2.7.

Tested with a number of images I have and it seems to work.

Thanks for the suggestion!
